export const OBTER_PROJETOS = "OBTER_PROJETOS";
export const CADASTRAR_PROJETOS = "CADASTRAR_PROJETOS";
export const ALTERAR_PROJETOS = "ALTERAR_PROJETOS";
export const DELETAR_PROJETOS = "DELETAR_PROJETOS";

export const OBTER_TAREFAS = "OBTER_TAREFAS";
export const CADASTRAR_TAREFAS = "CADASTAR_TAREFAS";
export const ALTERAR_TAREFAS = "ALTERAR_TAREFAS";
