export const OBTER_PROJETOS = "OBTER_PROJETOS"
export const CADASTRAS_PROJETOS = "CADASTRAS_PROJETOS"
export const ALTERAR_PROJETOS = "ALTERAR_PROJETOS"
export const DELETAR_PROJETOS = "DELETAR_PROJETOS"