export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const EDITAR_PROJETO = 'EDITAR_PROJETO'
export const EXCLUIR_PROJETO = 'EXCLUIR_PROJETO'
export const DEFINIR_PROJETO = 'DEFINIR_PROJETO'

export const NOTIFICAR = 'NOTIFICAR'